### ISSUE TITLE
nested tabboxes

### ISSUE THREAD

**Issue by speedplane2248** [otvv/fgui#12]
i may be stupid, however i dont understand why this code won't work. it compiles fully, however with it not commented, it crashes.
`ADD_GROUPBOX(vars::container["#vbox"], 15, 40, "aim", 260, 370, title_font, vars::container["#window"], 0, false, false, false);
		ADD_CONTROLLER(vars::container["#vbox"], vars::tabs["#tab_panel"]);
		/*
		REGISTER_TAB(vars::tabs["#visuals"], 7, 1, fgui::tab_layout::HORIZONTAL, title_font, vars::container["#aimbotbox"], 0	);
		ADD_TAB(vars::tabs["#visuals"], "team"); {
		}
		ADD_TAB(vars::tabs["#visuals"], "enemy"); {
		}
		ADD_TAB(vars::tabs["#visuals"], "priority"); {
		}
		ADD_TAB(vars::tabs["#visuals"], "friend"); {
			ADD_LABEL(vars::label["#joe"], 15, 15, "piss. piss in your asss!", fgui::label_type::TEXT, title_font, vars::container["#visuals"], 3);
		}
		ADD_TAB(vars::tabs["#visuals"], "viewmodel"); {
		}
		ADD_TAB(vars::tabs["#visuals"], "localplayer"); {
		}
		*/`

it's inside of a tabbox. please correct if i'm doing something stupid.

i'll add an image, as it looks like github code formatting sux

https://cdn.discordapp.com/attachments/611804250833420307/643996378715914280/image.png

**Comment by otvv** [comment]
Take a look at your label initialization. Also I really recommend using pointers instead of maps. The logic is probably wrong, that could be the reason you're crashing. (Using maps can be confusing sometimes) I recommend you to try to run this code piece by piece until you crash, so you can pinpoint what is causing it.

**Comment by speedplane2248** [comment]
okay. i'll try that out as soon as I get a chance. thanks!

**Comment by otvv** [comment]
No problem!
