### ISSUE TITLE
Crashing on inject sometimes

### ISSUE THREAD

**Issue by wifiman1337** [otvv/fgui#14]
most times when i inject i crash on this line
`inline fgui::state get_state() const noexcept {
			return m_opened;
		}`

I cant figure out a way around it

**Comment by otvv** [comment]
Show me the call stack. (In other words: what element lead to this crash.)

**Comment by wifiman1337** [comment]
I think its actually my lock cursor hook 
```
void __stdcall hooks::lock_cursor::hook() {//crash
	if (vars::container["#window"]->get_state()) {
		interfaces::surface->unlock_cursor();
		return;

		interfaces::inputsystem->enable_input(false);
	}
	else {
		interfaces::inputsystem->enable_input(true);
	}

	return lock_cursor_original(interfaces::surface);
}
```
but it crashes sometimes when it returns container state

**Comment by otvv** [comment]
This kind of crash are usually due to a null pointer, make sure that the container is being initialized correctly and the "name/token" on the unordered_map is correct as well.

**Comment by wifiman1337** [comment]
okay thanks, I got it fixed :)

**Comment by wifiman1337** [comment]
1 more question I was wondering how I could make it so if a checkbox is ticked to show for example a slider, ive tried with if statements but it doesn't appear

**Comment by otvv** [comment]
`ADD_CONTROLLER(checkbox, slider)`
And then on the "page" of the slider you put true or false

**Comment by wifiman1337** [comment]
thank you! great GUI

**Comment by otvv** [comment]
thank you!
i'm closing the issue now, any questions feel free to contact me on discord or here.
