### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by jackieyiwu** [otvv/fgui#15]
How can i use it with another language and change the fonts. I cant import  TTF.

**Comment by otvv** [comment]
Hi, thank you for your feedback!

The library can't load a TTF file directly. It can only load fonts that are already installed on your computer.
And about the "language support", I'm assuming that you meant support for special glyphs (Chinese, Japanese, Russian, etc). The library doesn't support wide chars for now, but it's something that will be supported at some point.
