### ISSUE TITLE
crashing with input::get_key_state

### ISSUE THREAD

**Issue by designer1337** [otvv/fgui#2]
as title says, can't get fgui to work due to this crash, using surface

is_button_down() code 
```
	bool is_button_down(int code) {
		using original_fn = bool(__thiscall*)(void*, int);
		return (*(original_fn * *)this)[15](this, code);
	}
```

call stack:
https://i.imgur.com/LlEj7Mi.png

**Comment by designer1337** [comment]
edit: throws me to this func after pressing home key
```
	void draw_colored_text(unsigned long font, int x, int y, int red, int green, int blue, int alpha, const char* text) {
		using original_fn = void(__thiscall*)(i_surface*, unsigned long, int, int, int, int, int, int, const char*);
		return (*(original_fn * *)this)[163](this, font, x, y, red, green, blue, alpha, text);
	}
```

call stack:
https://i.imgur.com/CM0RvxT.png

**Comment by otvv** [comment]
Does it crash whenever you press a key or it crashes when you inject your cheat? The callback wasn't very helpful, since it didn't show me where on the framework is the call for get_key_state coming from.

**Comment by designer1337** [comment]
> Does it crash whenever you press a key or it crashes when you inject your cheat? The callback wasn't very helpful, since it didn't show me where on the framework is the call for get_key_state coming from.

It's crashing everytime if press menu key (default home key), i guess everything with is_button_down is fine cuz it's working now, but it's crashing on draw_colored_text

**Comment by otvv** [comment]
> It's crashing everytime if press menu key (default home key), i guess everything with is_button_down is fine cuz it's working now, but it's crashing on draw_colored_text

Yeah, this draw_colored_function doesn't seem to work on Windows on the same way it works on Linux. (Using just the vtable index.) I would suggest to just use the other method of drawing text on surface.

```cpp
draw_set_text_pos(x, y);
draw_set_text_font(font);
draw_set_text_color(color.r(), color.g(), color.b() color.a( ));
draw_print_text(text.c_str(), string_length(text.c_str());
```

**Comment by designer1337** [comment]
> > It's crashing everytime if press menu key (default home key), i guess everything with is_button_down is fine cuz it's working now, but it's crashing on draw_colored_text
> 
> Yeah, this draw_colored_function doesn't seem to work on Windows on the same way it works on Linux. (Using just the vtable index.) I would suggest to just use the other method of drawing text on surface.
> 
> ```c++
> draw_set_text_pos(x, y);
> draw_set_text_font(font);
> draw_set_text_color(color.r(), color.g(), color.b() color.a( ));
> draw_print_text(text.c_str(), string_length(text.c_str());
> ```

got it working by replacing draw_text func:

```
void draw::text(int x, int y, fgui::color color, unsigned long font, std::string_view text) {
	const auto converted_text = std::wstring(text.begin(), text.end());

	interfaces::surface->set_text_color(color.m_red, color.m_green, color.m_blue, color.m_alpha);
	interfaces::surface->draw_text_font(font);
	interfaces::surface->draw_text_pos(x, y);
	interfaces::surface->draw_render_text(converted_text.c_str(), wcslen(converted_text.c_str()));
}

```

but seems like i have problems with few drawing functions, cuz it looks like this:
https://i.imgur.com/9RUIz2l.png

**Comment by otvv** [comment]
Thats weird.. Can you show me your render manager? Or is it the same as the one from ruvi-sdk?

**Comment by designer1337** [comment]
> Thats weird.. Can you show me your render manager? Or is it the same as the one from ruvi-sdk?

it's from ruvi with some changes
https://pastebin.com/Vqf0Jrkp

isurface:
https://pastebin.com/SMwqSRYz

idk if this might be a issue but im not setting m_bClippingEnabled to true/false cuz i can't find actual one for windows

**Comment by otvv** [comment]
Try setting up m_bClippingEnabled, like I do on ruvi
 
```cpp
 *csgo::vgui_surface->m_bClippingEnabled() = true;
 fgui::handler::render_window();
 *csgo::vgui_surface->m_bClippingEnabled() = false;
```
The offset on Windows should be `0x280`.

**Comment by designer1337** [comment]
> Try setting up m_bClippingEnabled, like I do on ruvi
> 
> ```c++
>  *csgo::vgui_surface->m_bClippingEnabled() = true;
>  fgui::handler::render_window();
>  *csgo::vgui_surface->m_bClippingEnabled() = false;
> ```
> 
> The offset on Windows should be `0x280`.

got it working!
https://i.imgur.com/AgJOiDb.png


the problem was

```
void draw::outline(int x, int y, int w, int h, fgui::color color) {

	interfaces::surface->set_drawing_color(color.m_red, color.m_green, color.m_blue,
		color.m_alpha);
	interfaces::surface->draw_outlined_rect(x, y, w, h);
	//	interfaces::surface->draw_outlined_rect(x, y, x + w, y + h);
}
```

```
	void draw_outlined_rect(int x, int y, int w, int h) {
		using original_fn = void(__thiscall*)(i_surface*, int, int, int, int);
		return (*(original_fn * *)this)[18](this, x, y, x + w, y + h); // cuz im doing my math already in surface class, same for filled rect
	}
```

great framework, thanks for ur help! <3

**Comment by otvv** [comment]
> got it working!
> https://i.imgur.com/AgJOiDb.png
> 
> the problem was
> 
> ```
> void draw::outline(int x, int y, int w, int h, fgui::color color) {
> 
> 	interfaces::surface->set_drawing_color(color.m_red, color.m_green, color.m_blue,
> 		color.m_alpha);
> 	interfaces::surface->draw_outlined_rect(x, y, w, h);
> 	//	interfaces::surface->draw_outlined_rect(x, y, x + w, y + h);
> }
> ```
> 
> ```
> 	void draw_outlined_rect(int x, int y, int w, int h) {
> 		using original_fn = void(__thiscall*)(i_surface*, int, int, int, int);
> 		return (*(original_fn * *)this)[18](this, x, y, x + w, y + h); // cuz im doing my math already in surface class, same for filled rect
> 	}
> ```
> 
> great framework, thanks for ur help! <3

No problem! Glad I could help.
