### ISSUE TITLE
multibox issue

### ISSUE THREAD

**Issue by depressedkid** [otvv/fgui#20]
when you try to select the item in the multibox it does not get selected

**Comment by otvv** [comment]
Are you using the legacy version?

**Comment by depressedkid** [comment]
my bad i am using a really old version i had
is there benefits for me switching versions because i coded a whole menu in the older one and had no problems with it just fixed this problem in the old version

what is the stuff that got updated visual improvements?

**Comment by otvv** [comment]
I don't recommend using the legacy version, since there's a lot of bugs and broken stuff. Everything you need to implement FGUI V2 is here on this repository.

**Comment by otvv** [comment]
Feel free to join the Discord server if you have any questions.
