### ISSUE TITLE
Really bad way to deal with shift held numbers and such

### ISSUE THREAD

**Issue by jakeau** [otvv/fgui#9]
Really bad way to deal with !@#$% etc. I couldn't think of a better way to do it. 

However, thought this may help.

`if (fgui::input_system::key_held(fgui::external::KEY_LSHIFT) || fgui::input_system::key_held(fgui::external::KEY_RSHIFT))
				{
					if (input.compare(xor("1")) == 0)
					{
						input = xor ("!");
					}
					else if (input.compare( xor ("2")) == 0)
					{
						input = xor ("@");
					}
					else if (input.compare( xor ("3")) == 0)
					{
						input = xor ("#");
					}
					else if (input.compare( xor ("4")) == 0)
					{
						input = xor ("$");
					}
					else if (input.compare( xor ("5")) == 0)
					{
						input = xor ("%");
					}
					else if (input.compare( xor ("6")) == 0)
					{
						input = xor ("^");
					}
					else if (input.compare( xor ("7")) == 0)
					{
						input = xor ("&");
					}
					else if (input.compare( xor ("8")) == 0)
					{
						input = xor ("*");
					}
					else if (input.compare( xor ("9")) == 0)
					{
						input = xor ("(");
					}
					else if (input.compare( xor ("0")) == 0)
					{
						input = xor (")");
					}
					else if (input.compare( xor ("-")) == 0)
					{
						input = xor ("_");
					}
					else if (input.compare( xor ("=")) == 0)
					{
						input = xor ("+");
					}
					else if (input.compare( xor ("[")) == 0)
					{
						input = xor ("{");
					}
					else if (input.compare( xor ("]")) == 0)
					{
						input = xor ("}");
					}
					else if (input.compare( xor ("\\")) == 0)
					{
						input = xor ("|");
					}
					else if (input.compare( xor (";")) == 0)
					{
						input = xor (":");
					}
					else if (input.compare( xor ("'")) == 0)
					{
						input = xor ("\"");
					}
					else if (input.compare( xor (",")) == 0)
					{
						input = xor ("<");
					}
					else if (input.compare( xor (".")) == 0)
					{
						input = xor (">");
					}
					else if (input.compare( xor ("/")) == 0)
					{
						input = xor ("?");
					}
					else if (input.compare( xor ("`")) == 0)
					{
						input = xor ("~");
					}
				}`

**Comment by otvv** [comment]
Yeah, that's really ghetto. You could make a look-up table for all those characters.
Thank you anyways, I'll look into implementing something like that in the future.
